/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksIndexRouteImport } from './routes/decks.index'
import { Route as DecksNewRouteImport } from './routes/decks.new'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksNewRoute = DecksNewRouteImport.update({
  id: '/decks/new',
  path: '/decks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/new': typeof DecksNewRoute
  '/decks': typeof DecksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/new': typeof DecksNewRoute
  '/decks': typeof DecksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/new': typeof DecksNewRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/study'
    | '/decks/$deckId'
    | '/decks/new'
    | '/decks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/study'
    | '/decks/$deckId'
    | '/decks/new'
    | '/decks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/study'
    | '/decks/$deckId'
    | '/decks/new'
    | '/decks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudyRoute: typeof StudyRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  DecksNewRoute: typeof DecksNewRoute
  DecksIndexRoute: typeof DecksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/new': {
      id: '/decks/new'
      path: '/decks/new'
      fullPath: '/decks/new'
      preLoaderRoute: typeof DecksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudyRoute: StudyRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  DecksNewRoute: DecksNewRoute,
  DecksIndexRoute: DecksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
